apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  # these are replica set labels
  labels:
    purpose: ingress-demo
    project: roboshop
    app: app1
spec:
  replicas: 2
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: ingress-demo
      project: roboshop
      app: app1
  # pod definition
  template:
    metadata:
      labels:
        # purpose: dp-demo
        purpose: ingress-demo
        project: roboshop
        app: app1
    spec:
      containers:
      - name: nginx
        image: surendevops75/app1:v1
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    purpose: ingress-demo
    project: roboshop
    app: app1
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:231298815636:certificate/dd4962e6-db71-4122-965c-ceaa89516813
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Project=roboshop
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
  - host: "app1.surendevops.fun"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app1
            port:
              number: 80